CREATE TABLE IF NOT EXISTS url
(
    id    SERIAL PRIMARY KEY,
    alias TEXT NOT NULL UNIQUE,
    url   TEXT NOT NULL UNIQUE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_alias ON url (alias);
CREATE UNIQUE INDEX IF NOT EXISTS idx_url ON url (url);