env: "local"
grpc:
  address: ":44044"
  timeout: 10s

http:
  address: ":8090"

db:
  host: "localhost"
  port: 5436
  user: "caxap"
  password: "1234"
  dbname: "db"
  sslmode: "disable"

url_generator:
  max_attempt: 15 # Максимальное количество попыток создать уникальный alias
  length: 10